module @jit__allocate attributes {mhlo.num_partitions = 4 : i32, mhlo.num_replicas = 1 : i32} {
  sdy.mesh @mesh = <["data"=1, "model"=4]> loc(#loc)
  func.func public @main() -> (tensor<14813x32x4x2x128xbf16> {jax.result_info = "result", sdy.sharding = #sdy.sharding<@mesh, [{}, {}, {"model"}, {}, {}]>}) {
    %cst = stablehlo.constant dense<0.000000e+00> : tensor<bf16> loc(#loc)
    %0 = stablehlo.broadcast_in_dim %cst, dims = [] : (tensor<bf16>) -> tensor<14813x32x4x2x128xbf16> loc(#loc30)
    return %0 : tensor<14813x32x4x2x128xbf16> loc(#loc)
  } loc(#loc)
} loc(#loc)
#loc = loc(unknown)
#loc1 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/runner/kv_cache.py":72:15 to 75:9)
#loc2 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/runner/kv_cache.py":80:25 to :43)
#loc3 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/runner/kv_cache_manager.py":190:23 to 198:13)
#loc4 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/runner/tpu_jax_runner.py":321:8 to :66)
#loc5 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/worker/tpu_worker_jax.py":294:8 to :67)
#loc6 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/vllm/v1/worker/worker_base.py":327:12 to :63)
#loc7 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/vllm/utils/__init__.py":2977:11 to :32)
#loc8 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py":74:20 to :72)
#loc9 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/vllm/v1/executor/abstract.py":77:8 to :79)
#loc10 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/vllm/v1/engine/core.py":239:8 to :68)
#loc11 = loc("create_kv_caches.<locals>._allocate"(#loc1))
#loc12 = loc("create_kv_caches"(#loc2))
#loc13 = loc("KVCacheManager.initialize_kv_cache"(#loc3))
#loc14 = loc("TPUModelRunner.initialize_kv_cache"(#loc4))
#loc15 = loc("TPUWorker.initialize_from_config"(#loc5))
#loc16 = loc("WorkerWrapperBase.initialize_from_config"(#loc6))
#loc17 = loc("run_method"(#loc7))
#loc18 = loc("UniProcExecutor.collective_rpc"(#loc8))
#loc19 = loc("Executor.initialize_from_config"(#loc9))
#loc20 = loc("EngineCore._initialize_kv_caches"(#loc10))
#loc21 = loc(callsite(#loc19 at #loc20))
#loc22 = loc(callsite(#loc18 at #loc21))
#loc23 = loc(callsite(#loc17 at #loc22))
#loc24 = loc(callsite(#loc16 at #loc23))
#loc25 = loc(callsite(#loc15 at #loc24))
#loc26 = loc(callsite(#loc14 at #loc25))
#loc27 = loc(callsite(#loc13 at #loc26))
#loc28 = loc(callsite(#loc12 at #loc27))
#loc29 = loc(callsite(#loc11 at #loc28))
#loc30 = loc("jit(_allocate)/broadcast_in_dim"(#loc29))
