#loc1 = loc("args[0]")
module @jit_broadcast_in_dim attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<i32> loc("args[0]")) -> (tensor<256xi32> {jax.result_info = "result"}) {
    %0 = stablehlo.broadcast_in_dim %arg0, dims = [] : (tensor<i32>) -> tensor<256xi32> loc(#loc31)
    return %0 : tensor<256xi32> loc(#loc)
  } loc(#loc)
} loc(#loc)
#loc = loc(unknown)
#loc2 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/runner/compilation_manager.py":43:17 to :45)
#loc3 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/runner/compilation_manager.py":101:19 to 102:55)
#loc4 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/runner/compilation_manager.py":155:12 to 158:64)
#loc5 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/runner/compilation_manager.py":75:12 to :49)
#loc6 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/runner/tpu_jax_runner.py":326:8 to :48)
#loc7 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/worker/tpu_worker_jax.py":232:8 to :41)
#loc8 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/vllm/utils/__init__.py":2977:11 to :32)
#loc9 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py":74:20 to :72)
#loc10 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/vllm/v1/executor/abstract.py":78:8 to :55)
#loc11 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/vllm/v1/engine/core.py":239:8 to :68)
#loc12 = loc("CompilationManager._create_dummy_tensor"(#loc2))
#loc13 = loc("CompilationManager._precompile_backbone_helper"(#loc3))
#loc14 = loc("CompilationManager._precompile_backbone_text_only"(#loc4))
#loc15 = loc("CompilationManager.capture_model"(#loc5))
#loc16 = loc("TPUModelRunner.capture_model"(#loc6))
#loc17 = loc("TPUWorker.compile_or_warm_up_model"(#loc7))
#loc18 = loc("run_method"(#loc8))
#loc19 = loc("UniProcExecutor.collective_rpc"(#loc9))
#loc20 = loc("Executor.initialize_from_config"(#loc10))
#loc21 = loc("EngineCore._initialize_kv_caches"(#loc11))
#loc22 = loc(callsite(#loc20 at #loc21))
#loc23 = loc(callsite(#loc19 at #loc22))
#loc24 = loc(callsite(#loc18 at #loc23))
#loc25 = loc(callsite(#loc17 at #loc24))
#loc26 = loc(callsite(#loc16 at #loc25))
#loc27 = loc(callsite(#loc15 at #loc26))
#loc28 = loc(callsite(#loc14 at #loc27))
#loc29 = loc(callsite(#loc13 at #loc28))
#loc30 = loc(callsite(#loc12 at #loc29))
#loc31 = loc("jit(broadcast_in_dim)/broadcast_in_dim"(#loc30))
