#loc1 = loc("args[0]")
module @jit_broadcast_in_dim attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<i32> loc("args[0]")) -> (tensor<256x512xi32> {jax.result_info = "result"}) {
    %0 = stablehlo.broadcast_in_dim %arg0, dims = [] : (tensor<i32>) -> tensor<256x512xi32> loc(#loc31)
    return %0 : tensor<256x512xi32> loc(#loc)
  } loc(#loc)
} loc(#loc)
#loc = loc(unknown)
#loc2 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/runner/block_table_jax.py":27:27 to 30:9)
#loc3 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/runner/block_table_jax.py":91:12 to 92:58)
#loc4 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/runner/block_table_jax.py":90:28 to 94:9)
#loc5 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/runner/input_batch_jax.py":84:27 to 90:9)
#loc6 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/runner/tpu_jax_runner.py":226:27 to 234:9)
#loc7 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/runner/tpu_jax_runner.py":111:8 to :27)
#loc8 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/tpu_inference/worker/tpu_worker_jax.py":143:28 to :74)
#loc9 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/vllm/v1/worker/worker_base.py":332:12 to :37)
#loc10 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/vllm/utils/__init__.py":2977:11 to :32)
#loc11 = loc("/home/eporat/benchmarking_qwen_omni_tpu/.venv/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py":74:20 to :72)
#loc12 = loc("BlockTable.__init__"(#loc2))
#loc13 = loc("MultiGroupBlockTable.__init__.<locals>.<listcomp>"(#loc3))
#loc14 = loc("MultiGroupBlockTable.__init__"(#loc4))
#loc15 = loc("InputBatch.__init__"(#loc5))
#loc16 = loc("TPUModelRunner._init_inputs"(#loc6))
#loc17 = loc("TPUModelRunner.__init__"(#loc7))
#loc18 = loc("TPUWorker.init_device"(#loc8))
#loc19 = loc("WorkerWrapperBase.init_device"(#loc9))
#loc20 = loc("run_method"(#loc10))
#loc21 = loc("UniProcExecutor.collective_rpc"(#loc11))
#loc22 = loc(callsite(#loc20 at #loc21))
#loc23 = loc(callsite(#loc19 at #loc22))
#loc24 = loc(callsite(#loc18 at #loc23))
#loc25 = loc(callsite(#loc17 at #loc24))
#loc26 = loc(callsite(#loc16 at #loc25))
#loc27 = loc(callsite(#loc15 at #loc26))
#loc28 = loc(callsite(#loc14 at #loc27))
#loc29 = loc(callsite(#loc13 at #loc28))
#loc30 = loc(callsite(#loc12 at #loc29))
#loc31 = loc("jit(broadcast_in_dim)/broadcast_in_dim"(#loc30))
